# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-04-01 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('describe', models.CharField(max_length=255)),
                ('rate', models.CharField(max_length=255)),
                ('disease', models.CharField(max_length=255)),
                ('drug', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('openid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('openid', models.CharField(max_length=255)),
                ('sex', models.CharField(default='女', max_length=255)),
            ],
        ),
    ]
