# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-04-01 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230401_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='age',
            field=models.CharField(max_length=255),
        ),
    ]
